# Generated by Django 4.1.13 on 2024-04-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.CharField(max_length=200, verbose_name='Ссылка на фото')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('count', models.IntegerField(verbose_name='Количество')),
            ],
        ),
    ]
